name: SalZH goes West 2016
favicon: null
layout_spectrum: 0.73741
typography_spectrum: 0.57477
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.3125
  lightness: 0.75
  saturation: 0.3176320376805961
  rhythmicContrast: 0.75
purpose: []
